### ISSUE TITLE
UNRECOVERABLE error - Nil Value - Waypoints Lua

### ISSUE THREAD

**Issue by asl97** [minetest-technic/unified_inventory#30] opened 2015-06-01 00:24 UTC
````
2015-05-31 18:42:38: ACTION[ServerThread]: (*name*) joins game. List of players: (*name*) (*name*)
2015-05-31 18:42:38: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
2015-05-31 18:42:38: ERROR[main]: ...t/(*server*)/bin/../mods/unified_inventory/waypoints.lua:37: attempt to index a nil value
2015-05-31 18:42:38: ERROR[main]: stack traceback:
2015-05-31 18:42:38: ERROR[main]: 	...t/(*server*)/bin/../mods/unified_inventory/waypoints.lua:37: in function 'get_formspec'
2015-05-31 18:42:38: ERROR[main]: 	...st/(*server*)/bin/../mods/unified_inventory/internal.lua:33: in function 'get_formspec'
2015-05-31 18:42:38: ERROR[main]: 	...st/(*server*)/bin/../mods/unified_inventory/internal.lua:131: in function 'set_inventory_formspec'
2015-05-31 18:42:38: ERROR[main]: 	...st/(*server*)/bin/../mods/unified_inventory/internal.lua:169: in function 'apply_filter'
2015-05-31 18:42:38: ERROR[main]: 	...t/(*server*)/bin/../mods/unified_inventory/callbacks.lua:18: in function <...t/(*server*)/bin/../mods/unified_inventory/callbacks.lua:10>
2015-05-31 18:42:38: ERROR[main]: 	/home/(*user*)/(*server*)/bin/../builtin/game/register.lua:341: in function </home/(*user*)/(*server*)/bin/../builtin/game/register.lua:329>

In thread 7f841ebbe880:
/home/(*user*)/minetest/src/server.cpp:505: void Server::step(float): A fatal error occurred: ...t/(*server*)/bin/../mods/unified_inventory/waypoints.lua:37: attempt to index a nil value
stack traceback:
	...t/(*server*)/bin/../mods/unified_inventory/waypoints.lua:37: in function 'get_formspec'
	...st/(*server*)/bin/../mods/unified_inventory/internal.lua:33: in function 'get_formspec'
	...st/(*server*)/bin/../mods/unified_inventory/internal.lua:131: in function 'set_inventory_formspec'
	...st/(*server*)/bin/../mods/unified_inventory/internal.lua:169: in function 'apply_filter'
	...t/(*server*)/bin/../mods/unified_inventory/callbacks.lua:18: in function <...t/(*server*)/bin/../mods/unified_inventory/callbacks.lua:10>
	/home/(*user*)/(*server*)/bin/../builtin/game/register.lua:341: in function </home/(*user*)/(*server*)/bin/../builtin/game/register.lua:329>
Debug stacks:
DEBUG STACK FOR THREAD 7f8403fff700:
#0  virtual void* EmergeThread::Thread()
(Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f841080c700:
#0  virtual void* ServerThread::Thread()
#1  void Server::Receive()
(Leftover data: #2  void Server::SendBlocks(float))
(Leftover data: #3  void RemoteClient::GetNextBlocks(ServerEnvironment*, EmergeManager*, float, std::vector<PrioritySortedBlockTransfer>&))
(Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
(Leftover data: #5  bool getCraftingResult(Inventory*, ItemStack&, bool, IGameDef*))
(Leftover data: #6  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f841ebbe880:
#0  int main(int, char**)
#1  Dedicated server branch
#2  void dedicated_server_loop(Server&, bool&)
#3  void Server::step(float)
````
where:
    `(*name*)` are players name
    `(*server*)` is the server folder
    `(*user*)` is the user name running the server process

____
~~i think it's because of https://github.com/minetest-technic/unified_inventory/blob/master/waypoints.lua#L238~~
(link gotten outdated)

shouldn't it be `waypoints_temp[player:get_player_name()] = {}`?

**Comment by VanessaE** [comment] 2015-10-08 10:55
This should be fixed now.

**Comment by asl97** [comment] 2015-10-09 03:50
i stopped playing again and this (iirc) isn't very easy to reproduce

however wouldn't it error at https://github.com/minetest-technic/unified_inventory/blob/5df353c299461a3ebda56f3fe38de5777678fba8/waypoints.lua#L90 ?

`waypoints_temp[player_name][1]` should be nil at that spot and `waypoints_temp[player_name][1].edit` would just explode.

**Comment by VanessaE** [comment] 2015-10-09 04:30
I was able to reproduce the issue on my Survival server by "borrowing" someone else's account who was having problems.  I have not been able to reproduce it since my fix, so I'm gonna call it good.

**Closed by VanessaE** 2015-10-09 04:30 UTC
