### ISSUE TITLE
UI fails to show drops of Wheat plant and Cotton plant from Minetest Game

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-technic/unified_inventory#73] opened 2016-08-16 21:23 UTC
The drops of the wheat and cotton plants from Minetest Game are not displayed at all.
So if you want to find out how to obtain wheat or cotton (=string), UI currently screws you. ;-)

I suspect the underlying issue here is that the wheat plant and cotton plant are hidden from the creative inventory and that UI “thinks” this implies they should also be hidden from the crafting guide, even if there is actually relevant information about them.

For reference, here are the correct drops of the fully grown wheat plant in 0.4.14.
- Guaranteed drops: 1 wheat, 1 wheat seed
- 50% chance: 1 additional wheat
- 50% chance: 1 additional wheat seed

Cotton plant is basically the same, just with cotton and cotton seed instead.

To avoid clutter, UI could maybe only show drops of the fully grown plant. However, I am not sure if it is a good idea to add mod/subgame-specific code into UI just to avoid clutter. :-/

**Comment by VanessaE** [comment] 2016-11-27 18:54
Dupe of #66.

**Closed by VanessaE** 2016-11-27 18:54 UTC
